name: spear-mtb
channels:
  - conda-forge
  - bioconda
dependencies:
  - bzip2=1.0.8
  - pip=22.3
  - python=3.10.6
  - pip:
    - biopython==1.79
    - gnomonicus==1.1.2
    - gumpy==1.0.15
    - numpy==1.23.4
    - pandas==1.5.1
    - piezo==0.3
    - scipy==1.9.3
    - tqdm==4.64.1
   